global:
  scrape_interval:     15s 
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "file_sd_config" 
    file_sd_configs:
      - files: 
        - /usr/local/prometheus/file_sd/sd_my_server.json
        refresh_interval: 5s

